name: Update Readme

on:
  schedule:
    - cron: "0 3 * * *" # Schedule at 3:00 AM UTC every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: Configure Git
        run: |
          git config --global user.email "dvipatwork@outlook.com"
          git config --global user.name "dvip1"
      - name: Run Script
        run: |
          chmod +x ./autoupdate.sh
          ./autoupdate.sh
      - name: Check for changes
        id: changes
        run: |
          git diff --exit-code && echo "No changes to commit" || echo "::set-output name=changed::true"
        continue-on-error: true

      - name: Commit and push if changed
        if: steps.changes.outputs.changed == 'true'
        uses: actions/setup-node@v3 # Use a different action for demonstration
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to main
        if: steps.changes.outputs.changed == 'true'
        run: |
          git add .
          git commit -m "Update readme"
          git push origin main
